server:
  port: 9876
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fullstackapp
    username: postgres
    password: brogoodabhi
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Additional properties (e.g., for transaction management, JPA settings, etc.) can be added here.

# Optional: You can define profiles for different environments (e.g., dev, prod) as well.
